### ISSUE TITLE
没有适配android 7.0 

### ISSUE THREAD

**Issue by zhouzl18** [chiclaim/AndroidUpdater#11]
能不能适配下android 7.0以及更高的版本，android 7.0加入了私有文件限制，通过downloadmanager获取的Uri不能获取PackageInfo

**Comment by zhouzl18** [comment]
我的手机是荣耀5C, android 7.0
我看到有个人和我同样的问题，也是这行代码
if (UpdaterUtils.compare(updaterConfig.getContext(), uri.getPath()))，在这里面获取的PackageInfo为null

**Comment by zhouzl18** [comment]
没问题了，是我这边测试有问题，唯一的问题就是在比较本地apk时，获取本地apk的PackageInfo为null。
我把UpdaterUtils.compare(Context context, String path)中的path设置为本地apk的绝对路径了，这样就能获取到PackageInfo了

**Comment by chiclaim** [comment]
@zhouzl18 好的，感谢反馈
