### ISSUE TITLE
在华为P20 pro 华为mete 20  华为meta 10 报错 

### ISSUE THREAD

**Issue by cnmao** [chiclaim/AndroidUpdater#13]
![image](https://user-images.githubusercontent.com/15217841/52623296-f20ffa80-2ee6-11e9-855c-d05c7fd1875d.png)

![image](https://user-images.githubusercontent.com/15217841/52623352-0d7b0580-2ee7-11e9-93b7-73c287b4ddcf.png)

获取应用状态的时候出现问题 ！

**Comment by cnmao** [comment]
版本为8 搞了大半年了 帮忙看下  18137503798 这个是我的电话， 关系到年后工作  谢谢

**Comment by chiclaim** [comment]
@cnmao你说的问题是什么问题？闪退吗？有日志的话，提供下。

**Comment by cnmao** [comment]
没有闪退 什么都没有 就是用户点击下载按键后 没有任何反应……

chiclaim <notifications@github.com>于2019年2月12日 周二17:25写道：

**Comment by cnmao** [comment]
那个地方爆异常 然后就没任何反应了

czsd Mao <maomengchong@gmail.com>于2019年2月12日 周二17:29写道：

**Comment by chiclaim** [comment]
@cnmao 我的手机就是最新的华为mate20，通知栏是有下载的。你说报异常，有异常日志吗？

**Comment by cnmao** [comment]
@chiclaim 没有了 ， 因为我技术总监原来说的， 有2个老板的手机出现问题。 让我修改 ， 我拿不到日志 。 然后我同事买了一个华为p20 pro 。 刚买回来，然后安装上去 是可以下载的， 等下一次我再在内网发包， 就出现问题，  点击后没有任何反应， 我看到那个 c.moveToFirst()这个方法 直接报了异常 ，  。

**Comment by chiclaim** [comment]
@cnmao 你是说开发的时候可以，发到内网就不行了？

**Comment by cnmao** [comment]
@chiclaim 你有什么思路没 ，她这一句报异常。

**Comment by cnmao** [comment]
我同事买回来的手机，  在应用宝先下载一个前年的最初版本， 然后下载打开后， 在界面上进行更新到阿里云上的最新包可以。 但是一段时间后， 估计是2个星期后， 等我再发新包的时候， 他就没办法下了

**Comment by chiclaim** [comment]
@cnmao 你自己本地可以改下版本号，改老一点，然后测试下更新功能，除了错你自己就可以看到了

**Comment by cnmao** [comment]
好的 谢谢你

chiclaim <notifications@github.com>于2019年2月13日 周三16:41写道：

**Comment by cnmao** [comment]
改老的话就没有问题！！！@chiclaim

**Comment by chiclaim** [comment]
@cnmao  那这个就不是这个库的问题了

**Comment by cnmao** [comment]
嗯

chiclaim <notifications@github.com> 于2019年2月15日周五 下午2:45写道：
