### ISSUE TITLE
华为荣耀10青春版 Android9 EMUI9.0.1 点击更新，没有反应

### ISSUE THREAD

**Issue by zgzygithub** [chiclaim/AndroidUpdater#16]
华为荣耀10青春版 Android9 EMUI9.0.1 点击更新，没有反应。
下载管理器中显示下载的apk“已加入队列”，隔了好久通知“下载失败”。

**Comment by Joerli** [comment]
I was having the same problem.
I solved the problem by putting **_android: usesCleartextTraffic = "true_"** inside the <application> tag in manifest.xml
