### ISSUE TITLE
为什么已经下载了，然后没安装，再次更新又会下载？根据打印的downloadID获取apk信息，apkinfo为null？是什么原因？

### ISSUE THREAD

**Issue by lihuanming** [chiclaim/AndroidUpdater#9]
为什么已经下载了，然后没安装，再次更新又会下载？根据打印的downloadID获取apk信息，apkinfo为null？是什么原因？

**Comment by chiclaim** [comment]
@lihuanming 例子会有日志输出的，没有安装，点击再次下载，应该是去获取本地的apk，本地的apk路径获取成功了吗？

**Comment by chiclaim** [comment]
这个问题还是android7.0或以上版本的查询出来的 uri不同：
